/**
 * Ayurvaidya Constants
 * Shared enums and constants across the application
 */

// ============================================
// ENUMS
// ============================================

export const Gender = {
    MALE: 'M',
    FEMALE: 'F',
    OTHER: 'O'
};

export const Prakriti = {
    VATA: 'VATA',
    PITTA: 'PITTA',
    KAPHA: 'KAPHA'
};

export const CaseStatus = {
    DRAFT: 'DRAFT',
    PENDING_REVIEW: 'PENDING_REVIEW',
    REVIEWED: 'REVIEWED',
    CLOSED: 'CLOSED'
};

export const CasePriority = {
    ROUTINE: 'ROUTINE',
    ELEVATED: 'ELEVATED',
    URGENT: 'URGENT'
};

export const AttachmentType = {
    LAB_REPORT: 'LAB_REPORT',
    PRESCRIPTION: 'PRESCRIPTION',
    IMAGE: 'IMAGE',
    OTHER: 'OTHER'
};

// ============================================
// DISCLAIMER
// ============================================

export const STANDARD_DISCLAIMER = `⚠️ GUIDANCE, NOT DIAGNOSIS

This information is generated to assist healthcare providers and does not constitute medical diagnosis, prescription, or treatment. All suggestions require validation by a qualified medical professional. The AI system provides decision support only — final clinical judgment rests with the treating physician.

Generated by Ayurvaidya CDSS v0.1 (Stage 1 - Stub Mode)`;

// ============================================
// AI PIPELINE STAGES
// ============================================

export const AIPipelineStage = {
    DATA_STRUCTURING: 'DATA_STRUCTURING',
    CLINICAL_SUMMARIZATION: 'CLINICAL_SUMMARIZATION',
    INTEGRATED_CARE_DRAFTING: 'INTEGRATED_CARE_DRAFTING',
    COST_OPTIMIZATION: 'COST_OPTIMIZATION',
    SAFETY_VALIDATION: 'SAFETY_VALIDATION'
};

// ============================================
// API RESPONSE CODES
// ============================================

export const ResponseCode = {
    SUCCESS: 'SUCCESS',
    CREATED: 'CREATED',
    BAD_REQUEST: 'BAD_REQUEST',
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
};

// ============================================
// PAGINATION DEFAULTS
// ============================================

export const Pagination = {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100
};
